version: '3'

#https://github.com/havfo/WEBRTC-to-SIP/blob/master/README.md
services:
  #https://hub.docker.com/r/kamailio/kamailio-ci
  kamailio:
    image: kamailio/kamailio-ci:5.4-alpine.debug
    container_name: kama
    network_mode: bridge                    # Only here to help testing
    ports:
      - "5060:5060/udp"                     # SIP UDP port
      - "5060:5060"                         # SIP TCP port
      - "5061:5061"                         # SIP TLS port
    hostname: "kamailio"
    volumes:
      - ./kamailio:/etc/kamailio
  rtpengine:
    image: readytalk/rtpengine-docker
    container_name: rtpengine
    network_mode: bridge
    ports:
      - "2223:2223/udp"
      - "2224:2224"
      - "2225:2225"
      - "30000-31000:30000-31000/udp"
    volumes:
      - ./rtpengine:/etc/rtpengine
  coturn:
    image: nazarpc/coturn
    container_name: coturn
    network_mode: bridge
    command:
      - "--restart=always"
      - "--name coturn"
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "65435-65535:65435-65535/udp"
    volumes:
      - type: bind
        source: ./turn/turnserver.conf
        target: /etc/turnserver.conf
volumes:
  teleconfsrv:                                # Persistent storage
