version: '3'

#https://github.com/havfo/WEBRTC-to-SIP/blob/master/README.md
services:
  #https://hub.docker.com/r/kamailio/kamailio-ci
  # - how to enable kamctl
  kamailio:
    image: kamailio/kamailio-ci:5.4-alpine.debug
    container_name: kama
#    network_mode: bridge                    # Only here to help testing
    ports:
      - "5060:5060/udp"                     # SIP UDP port
      - "5060:5060"                         # SIP TCP port
      - "5061:5061"                         # SIP TLS port
    hostname: "kamailio"
    volumes:
      - ./kamailio:/etc/kamailio
      - ./kamdb:/usr/local/kamdb
  rtpengine:
    image: freetechsolutions/rtpengine
    container_name: rtpengine
#    network_mode: bridge
    environment:
      - "ENV=devenv"
    ports:
      - "2223:2223/udp"
      - "2224:2224"
      - "2225:2225"
      - "30000-30020:30000-30020/udp"
    volumes:
      - ./rtpengine:/etc/rtpengine
  coturn:
    image: nazarpc/coturn
    container_name: coturn
#    network_mode: bridge
    command:
      - "--restart=always"
      - "--name coturn"
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "30050-30070:30050-30070/udp"
    environment:
      - "ANONYMOUS=0"
      - "USERNAME=turnuser"
      - "PASSWORD=turnpass"
      - "REALM=turnrealm"
      - "MIN_PORT=30050"
      - "MAX_PORT=30070"
volumes:
  teleconfsrv:                                # Persistent storage
